# Generated by Django 3.2.9 on 2021-12-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_ciudad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='precio',
            field=models.CharField(help_text='Ingrese el precio del coche', max_length=1000),
        ),
    ]
