# Generated by Django 3.2.9 on 2021-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_modelo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el precio del coche', max_digits=8),
        ),
    ]
